# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-14 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_remove_article_components'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='components',
            field=models.ManyToManyField(to='web.Component'),
        ),
    ]
