# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-15 10:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20170415_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='utworzony'),
        ),
        migrations.AlterField(
            model_name='article',
            name='published',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='opublikowany'),
        ),
        migrations.AlterField(
            model_name='article',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Section', verbose_name='dział'),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(default='created', max_length=100, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='tagi'),
        ),
    ]
