# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-15 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20170415_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='component',
            name='kind',
            field=models.CharField(default='fix', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='component',
            name='quote',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='url',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
