# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-25 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20170415_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='kind',
            field=models.CharField(choices=[('image', 'obraz'), ('quote', 'cytat'), ('text', 'kolumna'), ('video', 'film YT')], max_length=20),
        ),
    ]
