# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-02 00:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20170425_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='kind',
            field=models.CharField(choices=[('image', 'obraz'), ('quote', 'cytat'), ('paragraph', 'kolumna'), ('video', 'film YT')], max_length=20),
        ),
    ]
