# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-24 22:46
from __future__ import unicode_literals

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20170502_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cover',
            field=sorl.thumbnail.fields.ImageField(null=True, upload_to='web/media/covers', verbose_name='okładka'),
        ),
        migrations.AlterField(
            model_name='component',
            name='image',
            field=sorl.thumbnail.fields.ImageField(null=True, upload_to='web/media/images'),
        ),
        migrations.AlterField(
            model_name='component',
            name='kind',
            field=models.CharField(choices=[('image', 'obraz'), ('quote', 'cytat'), ('text', 'kolumna'), ('url', 'film YT')], max_length=20),
        ),
    ]
