# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-25 19:24
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_auto_20170524_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cover',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='web/media/covers', verbose_name='okładka'),
        ),
        migrations.AlterField(
            model_name='component',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='web/media/images'),
        ),
    ]
